# Railway configuration
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "java -cp .:out:lib/gson-2.10.1.jar Main"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = "8000"
