# Railway configuration
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "/bin/bash /app/start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "always"

# Volume for persistent data
[volumes]
data = "/app/data"

[env]
PORT = "8000"
GRAPH_DATA_PATH = "/app/data/graph.json"
