services:
  - type: web
    name: rekno-knowledge-graph
    env: docker
    plan: free
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: JAVA_OPTS
        value: -Xmx256m
